import { AssessmentQuestion } from '../types';

export const BASELINE_QUESTIONS: AssessmentQuestion[] = [
  // 1. JAVA (MCQ)
  {
    id: 'java-q1',
    skill: 'Java',
    type: 'mcq',
    prompt: 'In Java, how does the memory management of a String literal created with `String s = "hello";` differ from `String s = new String("hello");`?',
    options: [
      'Both instances are created in the general heap with identical references.',
      'The literal is retrieved from or stored in the String Constant Pool, while `new String()` always allocates a new object on the heap.',
      '`new String()` allocates in the Stack frame, while literals go to Metaspace.',
      'Literals are immutable, whereas strings created with `new` can be modified in-place.'
    ],
    correctIndex: 1,
    explanation: 'String literals are interned in the String Constant Pool to conserve memory. Using `new String()` forces a separate heap object creation.',
    difficulty: 'intermediate'
  },
  // 2. JAVA (Coding)
  {
    id: 'java-q2',
    skill: 'Java',
    type: 'coding',
    prompt: 'Implement a thread-safe Singleton pattern in Java using Double-Checked Locking. Complete the `getInstance()` method.',
    starterCode: `public class DatabaseConnection {
    private static volatile DatabaseConnection instance;
    private DatabaseConnection() {}

    public static DatabaseConnection getInstance() {
        // Complete the double-checked locking logic
        
    }
}`,
    expectedKeywords: ['if', 'synchronized', 'DatabaseConnection.class', 'instance == null', 'new DatabaseConnection'],
    rubric: 'Check for null check before synchronized block, synchronized on class lock, second null check inside block, and volatile assignment.',
    difficulty: 'advanced'
  },
  // 3. DSA (MCQ)
  {
    id: 'dsa-q1',
    skill: 'DSA',
    type: 'mcq',
    prompt: 'What is the worst-case time complexity of inserting `n` elements into a Binary Search Tree (BST) that is NOT self-balancing?',
    options: [
      'O(log n)',
      'O(n log n)',
      'O(n^2)',
      'O(n)'
    ],
    correctIndex: 2,
    explanation: 'If inputs are already sorted, an unbalancing BST degenerates into a linked list of height n, making n sequential insertions take O(1 + 2 + ... + n) = O(n^2).',
    difficulty: 'intermediate'
  },
  // 4. DSA (Coding / Algorithm)
  {
    id: 'dsa-q2',
    skill: 'DSA',
    type: 'coding',
    prompt: 'Write an optimal solution in Java or pseudocode to find two numbers in an integer array `nums` that add up to a specific `target`. Return their indices. Target time complexity: O(n).',
    starterCode: `public int[] twoSum(int[] nums, int target) {
    Map<Integer, Integer> map = new HashMap<>();
    // your implementation here
    
}`,
    expectedKeywords: ['containsKey', 'target - nums[i]', 'put', 'HashMap'],
    rubric: 'Should use a Hash Map for O(n) one-pass or two-pass lookup rather than O(n^2) nested loops.',
    difficulty: 'intermediate'
  },
  // 5. DSA (Scenario)
  {
    id: 'dsa-q3',
    skill: 'DSA',
    type: 'scenario',
    prompt: 'You are tasked with designing the "Top 100 Most Played Songs in the Last 24 Hours" for a music streaming service receiving 500,000 stream events per minute. Which data structures and caching approach would you choose and why?',
    rubric: 'Candidate should mention Count-Min Sketch or sliding window / bucketed timestamps, paired with a Min-Heap of size 100 for top-K, and Redis/In-memory caching.',
    difficulty: 'advanced'
  },
  // 6. SQL (MCQ)
  {
    id: 'sql-q1',
    skill: 'SQL',
    type: 'mcq',
    prompt: 'Consider two tables: `Users` (1,000 rows) and `Orders` (50,000 rows). You execute: `SELECT u.name, o.total FROM Users u LEFT JOIN Orders o ON u.id = o.user_id WHERE o.total > 100;`. What effect does the WHERE clause have on the result?',
    options: [
      'It preserves all 1,000 users, filling NULL for orders that do not match.',
      'It effectively converts the LEFT JOIN into an INNER JOIN, eliminating users without matching orders with total > 100.',
      'It raises a SQL syntax error because WHERE cannot filter on right-table columns in a LEFT JOIN.',
      'It applies the filter before the join occurs without affecting row retention.'
    ],
    correctIndex: 1,
    explanation: 'Filtering a column from the right table with a non-null condition in the WHERE clause discards the NULL rows generated by the LEFT JOIN, converting it into an INNER JOIN.',
    difficulty: 'intermediate'
  },
  // 7. SQL (Coding / Practical Query)
  {
    id: 'sql-q2',
    skill: 'SQL',
    type: 'coding',
    prompt: 'Given an `Employees` table with columns `(id, department_id, salary, name)`, write a query using a Window Function to find the 2nd highest salary in each department.',
    starterCode: `-- Write your SQL query here using DENSE_RANK() or ROW_NUMBER()
WITH RankedSalaries AS (
    SELECT id, department_id, salary,
           DENSE_RANK() OVER (
               PARTITION BY department_id 
               ORDER BY salary DESC
           ) as rnk
    FROM Employees
)
SELECT department_id, salary
FROM RankedSalaries
WHERE rnk = 2;`,
    expectedKeywords: ['DENSE_RANK', 'OVER', 'PARTITION BY', 'WHERE', 'rnk = 2'],
    rubric: 'Correct use of DENSE_RANK() or ROW_NUMBER() with PARTITION BY department_id and filter rnk = 2.',
    difficulty: 'advanced'
  },
  // 8. SQL (Scenario)
  {
    id: 'sql-q3',
    skill: 'SQL',
    type: 'scenario',
    prompt: 'A query `SELECT * FROM transactions WHERE user_id = 9812 AND status = "COMPLETED" ORDER BY created_at DESC;` is running slowly on a table with 20 million rows. How would you design an index to optimize this query, and what index scan type will the engine use?',
    rubric: 'Candidate should specify a composite B-Tree index on (user_id, status, created_at DESC). Mention avoiding index skip scan or filesort.',
    difficulty: 'advanced'
  },
  // 9. OOP (MCQ)
  {
    id: 'oop-q1',
    skill: 'OOP',
    type: 'mcq',
    prompt: 'Which SOLID principle is directly violated when a subclass overrides a base class method by throwing an `UnsupportedOperationException` because it cannot fulfill the base contract?',
    options: [
      'Single Responsibility Principle (SRP)',
      'Open/Closed Principle (OCP)',
      'Liskov Substitution Principle (LSP)',
      'Dependency Inversion Principle (DIP)'
    ],
    correctIndex: 2,
    explanation: 'The Liskov Substitution Principle dictates that objects of a superclass should be replaceable with objects of a subclass without breaking application correctness.',
    difficulty: 'intermediate'
  },
  // 10. OOP (Scenario / Design)
  {
    id: 'oop-q2',
    skill: 'OOP',
    type: 'open-ended',
    prompt: 'Explain the difference between the Strategy Pattern and the State Pattern. Even though both share nearly identical class diagrams, how do their design intents differ?',
    rubric: 'Should highlight: Strategy pattern is configured externally (client chooses algorithm), while State pattern transitions between states internally and models varying behavior based on lifecycle.',
    difficulty: 'intermediate'
  },
  // 11. GIT (MCQ)
  {
    id: 'git-q1',
    skill: 'Git',
    type: 'mcq',
    prompt: 'What happens when you run `git merge --squash feature-branch` into your current branch?',
    options: [
      'It creates a merge commit preserving all individual commit hashes from the feature branch.',
      'It combines all changes from feature-branch into the working directory and staging area as a single uncommitted change set, without creating an automatic merge commit.',
      'It rebases the feature branch commits on top of main and deletes the feature branch.',
      'It permanently purges the commit reflog on the remote origin.'
    ],
    correctIndex: 1,
    explanation: '`git merge --squash` combines the diff of all feature commits into staged modifications, allowing the developer to craft a clean, unified commit message before committing.',
    difficulty: 'intermediate'
  },
  // 12. GIT (Scenario)
  {
    id: 'git-q2',
    skill: 'Git',
    type: 'scenario',
    prompt: 'You committed sensitive database credentials in a commit pushed 3 commits ago on a shared staging branch. Describe the exact sequence of steps you would take to revoke the secret and clean the Git history.',
    rubric: 'Must state: First immediately rotate/revoke the credentials in the database (Git history rewrite alone is insufficient). Second, use `git filter-repo` or interactive rebase (`git rebase -i HEAD~4`) to remove the secret from commit history, followed by coordinated force push.',
    difficulty: 'advanced'
  },
  // 13. COMMUNICATION (Scenario)
  {
    id: 'comm-q1',
    skill: 'Communication',
    type: 'open-ended',
    prompt: 'During a sprint, you realize that an architectural requirement requested by the Product Manager will create a severe performance bottleneck for database writes. How do you communicate this trade-off to both the non-technical PM and the engineering lead?',
    rubric: 'Evaluates empathy, clarity, data-driven explanation, presenting alternatives with business impacts (latency vs feature scope), rather than purely defensive technical jargon.',
    difficulty: 'intermediate'
  },
  // 14. PROBLEM SOLVING (Scenario)
  {
    id: 'prob-q1',
    skill: 'Problem Solving',
    type: 'scenario',
    prompt: 'A microservice starts returning HTTP 504 Gateway Timeout errors intermittently every 15 minutes. CPU and Memory metrics on the containers look healthy (around 30%). Outline your step-by-step diagnostic workflow to isolate the root cause.',
    rubric: 'Candidate should mention inspecting downstream dependency latency, checking database connection pool saturation/threads, checking network timeouts/DNS, examining distributed tracing (e.g. Jaeger/Zipkin), and thread dumps for lock contention.',
    difficulty: 'advanced'
  },
  // 15. PROBLEM SOLVING (MCQ)
  {
    id: 'prob-q2',
    skill: 'Problem Solving',
    type: 'mcq',
    prompt: 'When diagnosing a memory leak in a Java application where Garbage Collection CPU spikes to 95% while throughput drops to zero, what is the primary diagnostic artifact you should capture?',
    options: [
      'The git commit diff of the last deployment.',
      'A Heap Dump (.hprof) captured using `jcmd` or `-XX:+HeapDumpOnOutOfMemoryError` and analyzed via Eclipse MAT or VisualVM.',
      'A network packet capture (pcap) using tcpdump.',
      'The stdout application logs from systemd.'
    ],
    correctIndex: 1,
    explanation: 'A Heap Dump captures the object graph at the time of memory pressure, allowing memory profiling tools to identify the dominator tree and leaking object references.',
    difficulty: 'intermediate'
  }
];
